controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml

user_list:
    path: /users
    controller: 'App\Controller\UserController::userList'

user_show:
    path: /user/{id}
    controller: 'App\Controller\UserController::userShow'

# config/routes.yaml

user_new:
    path: /user/new
    controller: 'App\Controller\UserController::newUser'


# config/routes.yaml
categorie_overzicht:
    path: /categorie
    controller: App\Controller\CategorieController::categorieShow
